### PR TITLE
added Eslint

### PR DESCRIPTION
**Pull request by ErickLemos**

### CODE REVIEW

**Comment by emibcn** [comment]
Nice!! Just a comment: could you use `yarn` instead of `npm` to add the dependencies? It's not a very good idea to have multiple package managers...

**Comment by ErickLemos** [comment]
OH, sorry! I will solve this!

**Review by emibcn — CHANGES_REQUESTED** [review]
Nice!! Just a comment: could you use `yarn` instead of `npm` to add the dependencies? It's not a very good idea to have multiple package managers...

**Comment by emibcn** [comment]
@ErickLemos Did you remove the original repo before the merge?

**Comment by ErickLemos** [comment]
oops, I will check and resolve this

**Comment by emibcn** [comment]
@ErickLemos: @sebas-alarconr wants to take it (if you don't want it anymore or you say nothing).

**Pull request closed without merging**
